using VRAcademy.Api.Domain;

namespace VRAcademy.Api.Services;

public static class SeedData
{
    private static readonly IReadOnlyDictionary<string, Guid> CourseIds = new Dictionary<string, Guid>
    {
        ["fire-protection"] = Guid.Parse("c3d3b41f-3017-4861-9d09-dbf349b1df43"),
        ["radioactive-materials"] = Guid.Parse("3a37e5bb-b46c-4d41-aeca-f5ad8a9c27e5"),
        ["chemical-waste"] = Guid.Parse("1f331493-79d8-42c5-b3d0-8c0b11330f27"),
        ["construction-waste"] = Guid.Parse("79c6aa17-f058-4329-9fd5-8ec279cc873d"),
        ["electronic-waste"] = Guid.Parse("4cce62e1-7849-4a1e-93dd-796043ebd18c"),
        ["biomedical-waste"] = Guid.Parse("30b016e2-cbe6-4fab-a6f5-6e3f47ee4cc8"),
        ["first-aid"] = Guid.Parse("bb8111a3-b58d-403a-9245-63961f2f291b"),
        ["working-at-heights"] = Guid.Parse("9145acd3-4b9b-44fb-bdfb-131bc25ed151"),
        ["forklift-safety"] = Guid.Parse("e31f5b2a-7cee-4731-a8f1-b5cc2f455a3e"),
        ["lockout-tagout"] = Guid.Parse("12996b73-45c7-456f-bdbb-617c47786e1b"),
        ["personal-protective-equipment"] = Guid.Parse("92bab77b-a886-4e43-b62c-746c047b4810"),
        ["chemical-safety"] = Guid.Parse("e3d1e155-8245-40ce-8820-158939f94d08"),
        ["electrical-safety"] = Guid.Parse("16b3545f-ed63-426a-88e3-64a016c44540"),
        ["confined-space-entry"] = Guid.Parse("a6d8459a-ccc9-436e-a670-72f6f925f7ed"),
        ["emergency-evacuation"] = Guid.Parse("a1859120-8276-4ec7-934a-0d1e0a102507"),
        ["industrial-machinery-safety"] = Guid.Parse("3259a124-f4d3-4159-a195-7bed362c5b06"),
        ["laboratory-safety"] = Guid.Parse("403f6449-7b47-4505-9bc3-d7f057b8b562"),
        ["hazardous-material-handling"] = Guid.Parse("5cadaf82-f481-4d73-9fdf-46bcb6ab5039"),
        ["construction-site-safety"] = Guid.Parse("9b599484-289e-4273-914a-95e2bf142bbf"),
        ["crane-suspended-loads"] = Guid.Parse("b7e813a7-c8b3-4348-a6f3-32b21df00bb9"),
        ["gas-leak-response"] = Guid.Parse("6c9def13-100e-492f-a464-773343a8d8b6"),
        ["warehouse-logistics-safety"] = Guid.Parse("8c8ce09e-bc0c-4254-be44-c382607d1a34"),
        ["drone-operation-fpv"] = Guid.Parse("448882ac-404c-4385-a47e-fa6f47c362a6"),
        ["drone-search-rescue"] = Guid.Parse("7a1791c9-805d-48c0-a8a5-977d2563e602")
    };

    public static List<TrainingScenario> CreateScenarios()
    {
        return new List<TrainingScenario>
        {
            new(
                Guid.Parse("c77fe939-98ee-4ca5-9f61-0d8f9d31f2b2"),
                "fire-protection",
                "Protivpozarna zastita",
                "Fire protection",
                "Prepoznavanje rizika, evakuacija, izbor opreme i pravilno reagovanje.",
                "Risk recognition, evacuation, equipment selection, and correct response.",
                "Safety",
                35),
            new(
                Guid.Parse("0d91384d-6c32-4f84-89c6-2bc378d01c18"),
                "radioactive-materials",
                "Upravljanje radioaktivnim materijalima",
                "Radioactive material handling",
                "Zastitna oprema, kontrola izlozenosti i proceduralne provere.",
                "Protective equipment, exposure control, and procedural checks.",
                "Hazardous materials",
                45),
            new(
                Guid.Parse("bf90d0a8-f907-40fc-9450-bc6ec237bcb9"),
                "chemical-waste",
                "Upravljanje hemijskim otpadom",
                "Chemical waste management",
                "Klasifikacija, obelezavanje, skladistenje i reakcija na prosipanje.",
                "Classification, labeling, storage, and spill response.",
                "Waste management",
                40),
            new(
                Guid.Parse("ffdb0364-47e2-4f4d-96b3-38675ba0938a"),
                "construction-waste",
                "Upravljanje gradjevinskim otpadom",
                "Construction waste management",
                "Razdvajanje materijala, bezbedan rad i pracenje tokova otpada.",
                "Material sorting, safe work, and waste flow tracking.",
                "Waste management",
                30),
            new(
                Guid.Parse("c391aa43-b3c6-4876-93db-fca11143e2b5"),
                "electronic-waste",
                "Upravljanje elektronskim otpadom",
                "Electronic waste management",
                "Sortiranje uredjaja, baterija, kablova i osetljivih komponenti.",
                "Sorting devices, batteries, cables, and sensitive components.",
                "Waste management",
                35),
            new(
                Guid.Parse("2a2d3685-1488-4d53-bd78-b82bb3a4c0d0"),
                "biomedical-waste",
                "Upravljanje biomedicinskim otpadom",
                "Biomedical waste management",
                "Razdvajanje, pakovanje i privremeno skladistenje zdravstvenog otpada.",
                "Separation, packaging, and temporary storage of healthcare waste.",
                "Healthcare safety",
                40),
            new(
                Guid.Parse("ccb1504c-7ecb-4558-8634-5dacfdb1aec4"),
                "first-aid",
                "Prva pomoc",
                "First Aid Training",
                "Procena situacije, KPR, kontrola krvarenja i pravilna upotreba AED uredjaja.",
                "Situation assessment, CPR, bleeding control, and correct use of an AED.",
                "Emergency response",
                30),
            new(
                Guid.Parse("6140c520-3b69-4019-923e-c2b402a05a96"),
                "working-at-heights",
                "Rad na visini",
                "Working at Heights",
                "Prepoznavanje rizika od pada, izbor opreme i bezbedno kretanje na visini.",
                "Fall hazard recognition, equipment selection, and safe movement at height.",
                "Work at height",
                30),
            new(
                Guid.Parse("80286c22-aa3f-457c-a308-f01542307c02"),
                "forklift-safety",
                "Bezbedno upravljanje viljuskarom",
                "Forklift Safety",
                "Pregled vozila, bezbedno upravljanje, rukovanje teretom i kretanje kroz radnu zonu.",
                "Vehicle inspection, safe operation, load handling, and workplace navigation.",
                "Industrial vehicles",
                30),
            new(
                Guid.Parse("f21e5460-36b5-4fe1-b3c7-2d1b9f0c6694"),
                "lockout-tagout",
                "Lockout/Tagout (LOTO)",
                "Lockout / Tagout",
                "Identifikacija izvora energije, izolacija, zakljucavanje i bezbedna provera opreme.",
                "Energy source identification, isolation, lockout, and safe equipment verification.",
                "Energy control",
                25),
            new(
                Guid.Parse("5666ad20-8b6e-497f-aa65-5d74003b9fc3"),
                "personal-protective-equipment",
                "Licna zastitna oprema",
                "Personal Protective Equipment",
                "Procena rizika, izbor, pregled, pravilno koriscenje i odrzavanje zastitne opreme.",
                "Risk assessment, selection, inspection, correct use, and maintenance of PPE.",
                "Personal protection",
                20),
            new(
                Guid.Parse("5eec99b0-5277-4d75-b2c4-8db0587495d1"),
                "chemical-safety",
                "Hemijska bezbednost",
                "Chemical Safety",
                "Prepoznavanje oznaka, bezbedno rukovanje hemikalijama i reagovanje pri prosipanju.",
                "Label recognition, safe chemical handling, and spill response.",
                "Chemical safety",
                30),
            new(
                Guid.Parse("e357ce88-65e5-413c-acb3-6b6a8ac35b08"),
                "electrical-safety",
                "Elektricna bezbednost",
                "Electrical Safety",
                "Prepoznavanje elektricnih rizika, bezbedan rad i reagovanje u vanrednim situacijama.",
                "Electrical hazard recognition, safe work practices, and emergency response.",
                "Electrical safety",
                30),
            new(
                Guid.Parse("60a98bf7-169c-42ef-ba03-fad6e6494c30"),
                "confined-space-entry",
                "Ulazak u zatvoreni prostor",
                "Confined Space Entry",
                "Procena prostora, merenje atmosfere, dozvola za rad i postupci spasavanja.",
                "Space assessment, atmospheric testing, work permits, and rescue procedures.",
                "Confined spaces",
                30),
            new(
                Guid.Parse("2f0339c9-8371-45d2-a844-2d208468dad4"),
                "emergency-evacuation",
                "Hitna evakuacija",
                "Emergency Evacuation",
                "Prepoznavanje alarma, izbor izlaza, pomoc kolegama i bezbedno okupljanje.",
                "Alarm recognition, exit selection, assisting others, and safe assembly.",
                "Emergency response",
                25),
            new(
                Guid.Parse("00cf06fa-8954-46c3-be43-2276b24864b4"),
                "industrial-machinery-safety",
                "Bezbedno rukovanje industrijskim masinama",
                "Safe Operation of Industrial Machinery",
                "Pregled masine, provera zastita, bezbedno pokretanje i zaustavljanje opreme.",
                "Machine inspection, guard checks, safe startup, operation, and shutdown.",
                "Machinery safety",
                30),
            new(
                Guid.Parse("5bd2218a-d12f-4489-a6f4-de90321c3289"),
                "laboratory-safety",
                "Bezbednost u laboratoriji",
                "Laboratory Safety",
                "Bezbedan rad sa uzorcima, laboratorijskom opremom, hemikalijama i kontaminacijom.",
                "Safe work with samples, laboratory equipment, chemicals, and contamination.",
                "Laboratory safety",
                30),
            new(
                Guid.Parse("a6f0a23f-0d19-4af4-b4a2-75525d82c53b"),
                "hazardous-material-handling",
                "Rukovanje opasnim materijalima",
                "Hazardous Material Handling",
                "Prijem, oznacavanje, razdvajanje, transport i skladistenje opasnih materijala.",
                "Receiving, labeling, segregation, transport, and storage of hazardous materials.",
                "Hazardous materials",
                30),
            new(
                Guid.Parse("3ba2f8b1-126d-4251-ae77-ea977be1304b"),
                "construction-site-safety",
                "Bezbednost na gradilistu",
                "Construction Site Safety",
                "Prepoznavanje rizika, bezbedno kretanje, radne zone, skele i kontrola pristupa.",
                "Hazard recognition, safe movement, work zones, scaffolding, and access control.",
                "Construction safety",
                30),
            new(
                Guid.Parse("493d682f-7cbd-445a-a18f-2a2d05f55434"),
                "crane-suspended-loads",
                "Rad u blizini dizalica i visecih tereta",
                "Working Near Cranes and Suspended Loads",
                "Planiranje dizanja, bezbedne zone, komunikacija i reagovanje pri nestabilnom teretu.",
                "Lift planning, exclusion zones, communication, and response to unstable loads.",
                "Lifting operations",
                30),
            new(
                Guid.Parse("2ecb069d-56eb-4b12-848e-6fb847f0352a"),
                "gas-leak-response",
                "Reagovanje pri curenju gasa",
                "Gas Leak Response",
                "Prepoznavanje curenja, aktiviranje alarma, izolacija zone i bezbedna evakuacija.",
                "Leak recognition, alarm activation, area isolation, and safe evacuation.",
                "Emergency response",
                30),
            new(
                Guid.Parse("a6bfca41-c56d-4d4d-a38c-016e94d8b841"),
                "warehouse-logistics-safety",
                "Bezbednost u skladistu i logistici",
                "Warehouse and Logistics Safety",
                "Bezbedno kretanje, slaganje tereta, rukovanje opremom i kontrola logistickih rizika.",
                "Safe movement, load stacking, equipment handling, and logistics risk control.",
                "Logistics safety",
                25),
            new(
                Guid.Parse("de341505-37ae-4dde-b647-7a2b7ae0094d"),
                "drone-operation-fpv",
                "Upravljanje dronom i FPV navigacija",
                "Drone Operation and FPV Navigation",
                "Predletna provera, bezbedno upravljanje, FPV navigacija i reagovanje na incidente.",
                "Pre-flight checks, safe operation, FPV navigation, and incident response.",
                "Drone operations",
                30),
            new(
                Guid.Parse("303c1d09-c3ac-4953-a47b-58329bea4bcc"),
                "drone-search-rescue",
                "Potraga i spasavanje uz pomoc drona",
                "Drone-Assisted Search and Rescue",
                "Planiranje misije, vazdusna pretraga, lociranje osobe i koordinacija spasavanja.",
                "Mission planning, aerial search, casualty location, and rescue coordination.",
                "Search and rescue",
                35)
        };
    }

    public static List<Course> CreateCourses(IReadOnlyCollection<TrainingScenario> scenarios)
    {
        return scenarios
            .Select(scenario => new Course(
                CourseIds[scenario.Code],
                scenario.Code,
                scenario.NameSr,
                scenario.NameEn,
                scenario.DescriptionSr,
                scenario.DescriptionEn,
                12,
                80,
                new[] { scenario.Id }))
            .ToList();
    }
}

