// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VRAcademy.Api.Persistence;

#nullable disable

namespace VRAcademy.Api.Persistence.Migrations
{
    [DbContext(typeof(TrainingDbContext))]
    [Migration("20261007194115_AddCatalogCourses")]
    partial class AddCatalogCourses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VRAcademy.Api.Persistence.Entities.AuthSessionEntity", b =>
                {
                    b.Property<string>("AccessToken")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AccessToken");

                    b.HasIndex("UserId");

                    b.ToTable("AuthSessions", (string)null);
                });

            modelBuilder.Entity("VRAcademy.Api.Persistence.Entities.CertificateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset>("ValidUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CertificateNumber")
                        .IsUnique();

                    b.HasIndex("CourseId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Certificates", (string)null);
                });

            modelBuilder.Entity("VRAcademy.Api.Persistence.Entities.CompanyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SubscriptionLevel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("VRAcademy.Api.Persistence.Entities.CourseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DescriptionSr")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("NameSr")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<int>("PassScore")
                        .HasColumnType("int");

                    b.Property<int>("ValidityMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3d3b41f-3017-4861-9d09-dbf349b1df43"),
                            Code = "fire-protection",
                            DescriptionEn = "Risk recognition, evacuation, equipment selection, and correct response.",
                            DescriptionSr = "Prepoznavanje rizika, evakuacija, izbor opreme i pravilno reagovanje.",
                            NameEn = "Fire protection",
                            NameSr = "Protivpozarna zastita",
                            PassScore = 80,
                            ValidityMonths = 12
                        },
                        new
                        {
                            Id = new Guid("3a37e5bb-b46c-4d41-aeca-f5ad8a9c27e5"),
                            Code = "radioactive-materials",
                            DescriptionEn = "Protective equipment, exposure control, and procedural checks.",
                            DescriptionSr = "Zastitna oprema, kontrola izlozenosti i proceduralne provere.",
                            NameEn = "Radioactive material handling",
                            NameSr = "Upravljanje radioaktivnim materijalima",
                            PassScore = 80,
                            ValidityMonths = 12
                        },
                        new
                        {
                            Id = new Guid("1f331493-79d8-42c5-b3d0-8c0b11330f27"),
                            Code = "chemical-waste",
                            DescriptionEn = "Classification, labeling, storage, and spill response.",
                            DescriptionSr = "Klasifikacija, obelezavanje, skladistenje i reakcija na prosipanje.",
                            NameEn = "Chemical waste management",
                            NameSr = "Upravljanje hemijskim otpadom",
                            PassScore = 80,
                            ValidityMonths = 12
                        },
                        new
                        {
                            Id = new Guid("79c6aa17-f058-4329-9fd5-8ec279cc873d"),
                            Code = "construction-waste",
                            DescriptionEn = "Material sorting, safe work, and waste flow tracking.",
                            DescriptionSr = "Razdvajanje materijala, bezbedan rad i pracenje tokova otpada.",
                            NameEn = "Construction waste management",
                            NameSr = "Upravljanje gradjevinskim otpadom",
                            PassScore = 80,
                            ValidityMonths = 12
                        },
                        new
                        {
                            Id = new Guid("4cce62e1-7849-4a1e-93dd-796043ebd18c"),
                            Code = "electronic-waste",
                            DescriptionEn = "Sorting devices, batteries, cables, and sensitive components.",
                            DescriptionSr = "Sortiranje uredjaja, baterija, kablova i osetljivih komponenti.",
                            NameEn = "Electronic waste management",
                            NameSr = "Upravljanje elektronskim otpadom",
                            PassScore = 80,
                            ValidityMonths = 12
                        },
                        new
                        {
                            Id = new Guid("30b016e2-cbe6-4fab-a6f5-6e3f47ee4cc8"),
                            Code = "biomedical-waste",
                            DescriptionEn = "Separation, packaging, and temporary storage of healthcare waste.",
                            DescriptionSr = "Razdvajanje, pakovanje i privremeno skladistenje zdravstvenog otpada.",
                            NameEn = "Biomedical waste management",
                            NameSr = "Upravljanje biomedicinskim otpadom",
                            PassScore = 80,
                            ValidityMonths = 12
                        },
                        new
                        {
                            Id = new Guid("bb8111a3-b58d-403a-9245-63961f2f291b"),
                            Code = "first-aid",
                            DescriptionEn = "Situation assessment, CPR, bleeding control, and correct use of an AED.",
                            DescriptionSr = "Procena situacije, KPR, kontrola krvarenja i pravilna upotreba AED uredjaja.",
                            NameEn = "First Aid Training",
                            NameSr = "Prva pomoc",
                            PassScore = 80,
                            ValidityMonths = 12
                        },
                        new
                        {
                            Id = new Guid("9145acd3-4b9b-44fb-bdfb-131bc25ed151"),
                            Code = "working-at-heights",
                            DescriptionEn = "Fall hazard recognition, equipment selection, and safe movement at height.",
                            DescriptionSr = "Prepoznavanje rizika od pada, izbor opreme i bezbedno kretanje na visini.",
                            NameEn = "Working at Heights",
                            NameSr = "Rad na visini",
                            PassScore = 80,
                            ValidityMonths = 12
                        },
                        new
                        {
                            Id = new Guid("e31f5b2a-7cee-4731-a8f1-b5cc2f455a3e"),
                            Code = "forklift-safety",
                            DescriptionEn = "Vehicle inspection, safe operation, load handling, and workplace navigation.",
                            DescriptionSr = "Pregled vozila, bezbedno upravljanje, rukovanje teretom i kretanje kroz radnu zonu.",
                            NameEn = "Forklift Safety",
                            NameSr = "Bezbedno upravljanje viljuskarom",
                            PassScore = 80,
                            ValidityMonths = 12
                        },
                        new
                        {
                            Id = new Guid("12996b73-45c7-456f-bdbb-617c47786e1b"),
                            Code = "lockout-tagout",
                            DescriptionEn = "Energy source identification, isolation, lockout, and safe equipment verification.",
                            DescriptionSr = "Identifikacija izvora energije, izolacija, zakljucavanje i bezbedna provera opreme.",
                            NameEn = "Lockout / Tagout",
                            NameSr = "Lockout/Tagout (LOTO)",
                            PassScore = 80,
                            ValidityMonths = 12
                        },
                        new
                        {
                            Id = new Guid("92bab77b-a886-4e43-b62c-746c047b4810"),
                            Code = "personal-protective-equipment",
                            DescriptionEn = "Risk assessment, selection, inspection, correct use, and maintenance of PPE.",
                            DescriptionSr = "Procena rizika, izbor, pregled, pravilno koriscenje i odrzavanje zastitne opreme.",
                            NameEn = "Personal Protective Equipment",
                            NameSr = "Licna zastitna oprema",
                            PassScore = 80,
                            ValidityMonths = 12
                        },
                        new
                        {
                            Id = new Guid("e3d1e155-8245-40ce-8820-158939f94d08"),
                            Code = "chemical-safety",
                            DescriptionEn = "Label recognition, safe chemical handling, and spill response.",
                            DescriptionSr = "Prepoznavanje oznaka, bezbedno rukovanje hemikalijama i reagovanje pri prosipanju.",
                            NameEn = "Chemical Safety",
                            NameSr = "Hemijska bezbednost",
                            PassScore = 80,
                            ValidityMonths = 12
                        },
                        new
                        {
                            Id = new Guid("16b3545f-ed63-426a-88e3-64a016c44540"),
                            Code = "electrical-safety",
                            DescriptionEn = "Electrical hazard recognition, safe work practices, and emergency response.",
                            DescriptionSr = "Prepoznavanje elektricnih rizika, bezbedan rad i reagovanje u vanrednim situacijama.",
                            NameEn = "Electrical Safety",
                            NameSr = "Elektricna bezbednost",
                            PassScore = 80,
                            ValidityMonths = 12
                        },
                        new
                        {
                            Id = new Guid("a6d8459a-ccc9-436e-a670-72f6f925f7ed"),
                            Code = "confined-space-entry",
                            DescriptionEn = "Space assessment, atmospheric testing, work permits, and rescue procedures.",
                            DescriptionSr = "Procena prostora, merenje atmosfere, dozvola za rad i postupci spasavanja.",
                            NameEn = "Confined Space Entry",
                            NameSr = "Ulazak u zatvoreni prostor",
                            PassScore = 80,
                            ValidityMonths = 12
                        },
                        new
                        {
                            Id = new Guid("a1859120-8276-4ec7-934a-0d1e0a102507"),
                            Code = "emergency-evacuation",
                            DescriptionEn = "Alarm recognition, exit selection, assisting others, and safe assembly.",
                            DescriptionSr = "Prepoznavanje alarma, izbor izlaza, pomoc kolegama i bezbedno okupljanje.",
                            NameEn = "Emergency Evacuation",
                            NameSr = "Hitna evakuacija",
                            PassScore = 80,
                            ValidityMonths = 12
                        },
                        new
                        {
                            Id = new Guid("3259a124-f4d3-4159-a195-7bed362c5b06"),
                            Code = "industrial-machinery-safety",
                            DescriptionEn = "Machine inspection, guard checks, safe startup, operation, and shutdown.",
                            DescriptionSr = "Pregled masine, provera zastita, bezbedno pokretanje i zaustavljanje opreme.",
                            NameEn = "Safe Operation of Industrial Machinery",
                            NameSr = "Bezbedno rukovanje industrijskim masinama",
                            PassScore = 80,
                            ValidityMonths = 12
                        },
                        new
                        {
                            Id = new Guid("403f6449-7b47-4505-9bc3-d7f057b8b562"),
                            Code = "laboratory-safety",
                            DescriptionEn = "Safe work with samples, laboratory equipment, chemicals, and contamination.",
                            DescriptionSr = "Bezbedan rad sa uzorcima, laboratorijskom opremom, hemikalijama i kontaminacijom.",
                            NameEn = "Laboratory Safety",
                            NameSr = "Bezbednost u laboratoriji",
                            PassScore = 80,
                            ValidityMonths = 12
                        },
                        new
                        {
                            Id = new Guid("5cadaf82-f481-4d73-9fdf-46bcb6ab5039"),
                            Code = "hazardous-material-handling",
                            DescriptionEn = "Receiving, labeling, segregation, transport, and storage of hazardous materials.",
                            DescriptionSr = "Prijem, oznacavanje, razdvajanje, transport i skladistenje opasnih materijala.",
                            NameEn = "Hazardous Material Handling",
                            NameSr = "Rukovanje opasnim materijalima",
                            PassScore = 80,
                            ValidityMonths = 12
                        },
                        new
                        {
                            Id = new Guid("9b599484-289e-4273-914a-95e2bf142bbf"),
                            Code = "construction-site-safety",
                            DescriptionEn = "Hazard recognition, safe movement, work zones, scaffolding, and access control.",
                            DescriptionSr = "Prepoznavanje rizika, bezbedno kretanje, radne zone, skele i kontrola pristupa.",
                            NameEn = "Construction Site Safety",
                            NameSr = "Bezbednost na gradilistu",
                            PassScore = 80,
                            ValidityMonths = 12
                        },
                        new
                        {
                            Id = new Guid("b7e813a7-c8b3-4348-a6f3-32b21df00bb9"),
                            Code = "crane-suspended-loads",
                            DescriptionEn = "Lift planning, exclusion zones, communication, and response to unstable loads.",
                            DescriptionSr = "Planiranje dizanja, bezbedne zone, komunikacija i reagovanje pri nestabilnom teretu.",
                            NameEn = "Working Near Cranes and Suspended Loads",
                            NameSr = "Rad u blizini dizalica i visecih tereta",
                            PassScore = 80,
                            ValidityMonths = 12
                        },
                        new
                        {
                            Id = new Guid("6c9def13-100e-492f-a464-773343a8d8b6"),
                            Code = "gas-leak-response",
                            DescriptionEn = "Leak recognition, alarm activation, area isolation, and safe evacuation.",
                            DescriptionSr = "Prepoznavanje curenja, aktiviranje alarma, izolacija zone i bezbedna evakuacija.",
                            NameEn = "Gas Leak Response",
                            NameSr = "Reagovanje pri curenju gasa",
                            PassScore = 80,
                            ValidityMonths = 12
                        },
                        new
                        {
                            Id = new Guid("8c8ce09e-bc0c-4254-be44-c382607d1a34"),
                            Code = "warehouse-logistics-safety",
                            DescriptionEn = "Safe movement, load stacking, equipment handling, and logistics risk control.",
                            DescriptionSr = "Bezbedno kretanje, slaganje tereta, rukovanje opremom i kontrola logistickih rizika.",
                            NameEn = "Warehouse and Logistics Safety",
                            NameSr = "Bezbednost u skladistu i logistici",
                            PassScore = 80,
                            ValidityMonths = 12
                        },
                        new
                        {
                            Id = new Guid("448882ac-404c-4385-a47e-fa6f47c362a6"),
                            Code = "drone-operation-fpv",
                            DescriptionEn = "Pre-flight checks, safe operation, FPV navigation, and incident response.",
                            DescriptionSr = "Predletna provera, bezbedno upravljanje, FPV navigacija i reagovanje na incidente.",
                            NameEn = "Drone Operation and FPV Navigation",
                            NameSr = "Upravljanje dronom i FPV navigacija",
                            PassScore = 80,
                            ValidityMonths = 12
                        },
                        new
                        {
                            Id = new Guid("7a1791c9-805d-48c0-a8a5-977d2563e602"),
                            Code = "drone-search-rescue",
                            DescriptionEn = "Mission planning, aerial search, casualty location, and rescue coordination.",
                            DescriptionSr = "Planiranje misije, vazdusna pretraga, lociranje osobe i koordinacija spasavanja.",
                            NameEn = "Drone-Assisted Search and Rescue",
                            NameSr = "Potraga i spasavanje uz pomoc drona",
                            PassScore = 80,
                            ValidityMonths = 12
                        });
                });

            modelBuilder.Entity("VRAcademy.Api.Persistence.Entities.CourseScenarioEntity", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CourseId", "ScenarioId");

                    b.HasIndex("ScenarioId");

                    b.ToTable("CourseScenarios", (string)null);

                    b.HasData(
                        new
                        {
                            CourseId = new Guid("c3d3b41f-3017-4861-9d09-dbf349b1df43"),
                            ScenarioId = new Guid("c77fe939-98ee-4ca5-9f61-0d8f9d31f2b2")
                        },
                        new
                        {
                            CourseId = new Guid("3a37e5bb-b46c-4d41-aeca-f5ad8a9c27e5"),
                            ScenarioId = new Guid("0d91384d-6c32-4f84-89c6-2bc378d01c18")
                        },
                        new
                        {
                            CourseId = new Guid("1f331493-79d8-42c5-b3d0-8c0b11330f27"),
                            ScenarioId = new Guid("bf90d0a8-f907-40fc-9450-bc6ec237bcb9")
                        },
                        new
                        {
                            CourseId = new Guid("79c6aa17-f058-4329-9fd5-8ec279cc873d"),
                            ScenarioId = new Guid("ffdb0364-47e2-4f4d-96b3-38675ba0938a")
                        },
                        new
                        {
                            CourseId = new Guid("4cce62e1-7849-4a1e-93dd-796043ebd18c"),
                            ScenarioId = new Guid("c391aa43-b3c6-4876-93db-fca11143e2b5")
                        },
                        new
                        {
                            CourseId = new Guid("30b016e2-cbe6-4fab-a6f5-6e3f47ee4cc8"),
                            ScenarioId = new Guid("2a2d3685-1488-4d53-bd78-b82bb3a4c0d0")
                        },
                        new
                        {
                            CourseId = new Guid("bb8111a3-b58d-403a-9245-63961f2f291b"),
                            ScenarioId = new Guid("ccb1504c-7ecb-4558-8634-5dacfdb1aec4")
                        },
                        new
                        {
                            CourseId = new Guid("9145acd3-4b9b-44fb-bdfb-131bc25ed151"),
                            ScenarioId = new Guid("6140c520-3b69-4019-923e-c2b402a05a96")
                        },
                        new
                        {
                            CourseId = new Guid("e31f5b2a-7cee-4731-a8f1-b5cc2f455a3e"),
                            ScenarioId = new Guid("80286c22-aa3f-457c-a308-f01542307c02")
                        },
                        new
                        {
                            CourseId = new Guid("12996b73-45c7-456f-bdbb-617c47786e1b"),
                            ScenarioId = new Guid("f21e5460-36b5-4fe1-b3c7-2d1b9f0c6694")
                        },
                        new
                        {
                            CourseId = new Guid("92bab77b-a886-4e43-b62c-746c047b4810"),
                            ScenarioId = new Guid("5666ad20-8b6e-497f-aa65-5d74003b9fc3")
                        },
                        new
                        {
                            CourseId = new Guid("e3d1e155-8245-40ce-8820-158939f94d08"),
                            ScenarioId = new Guid("5eec99b0-5277-4d75-b2c4-8db0587495d1")
                        },
                        new
                        {
                            CourseId = new Guid("16b3545f-ed63-426a-88e3-64a016c44540"),
                            ScenarioId = new Guid("e357ce88-65e5-413c-acb3-6b6a8ac35b08")
                        },
                        new
                        {
                            CourseId = new Guid("a6d8459a-ccc9-436e-a670-72f6f925f7ed"),
                            ScenarioId = new Guid("60a98bf7-169c-42ef-ba03-fad6e6494c30")
                        },
                        new
                        {
                            CourseId = new Guid("a1859120-8276-4ec7-934a-0d1e0a102507"),
                            ScenarioId = new Guid("2f0339c9-8371-45d2-a844-2d208468dad4")
                        },
                        new
                        {
                            CourseId = new Guid("3259a124-f4d3-4159-a195-7bed362c5b06"),
                            ScenarioId = new Guid("00cf06fa-8954-46c3-be43-2276b24864b4")
                        },
                        new
                        {
                            CourseId = new Guid("403f6449-7b47-4505-9bc3-d7f057b8b562"),
                            ScenarioId = new Guid("5bd2218a-d12f-4489-a6f4-de90321c3289")
                        },
                        new
                        {
                            CourseId = new Guid("5cadaf82-f481-4d73-9fdf-46bcb6ab5039"),
                            ScenarioId = new Guid("a6f0a23f-0d19-4af4-b4a2-75525d82c53b")
                        },
                        new
                        {
                            CourseId = new Guid("9b599484-289e-4273-914a-95e2bf142bbf"),
                            ScenarioId = new Guid("3ba2f8b1-126d-4251-ae77-ea977be1304b")
                        },
                        new
                        {
                            CourseId = new Guid("b7e813a7-c8b3-4348-a6f3-32b21df00bb9"),
                            ScenarioId = new Guid("493d682f-7cbd-445a-a18f-2a2d05f55434")
                        },
                        new
                        {
                            CourseId = new Guid("6c9def13-100e-492f-a464-773343a8d8b6"),
                            ScenarioId = new Guid("2ecb069d-56eb-4b12-848e-6fb847f0352a")
                        },
                        new
                        {
                            CourseId = new Guid("8c8ce09e-bc0c-4254-be44-c382607d1a34"),
                            ScenarioId = new Guid("a6bfca41-c56d-4d4d-a38c-016e94d8b841")
                        },
                        new
                        {
                            CourseId = new Guid("448882ac-404c-4385-a47e-fa6f47c362a6"),
                            ScenarioId = new Guid("de341505-37ae-4dde-b647-7a2b7ae0094d")
                        },
                        new
                        {
                            CourseId = new Guid("7a1791c9-805d-48c0-a8a5-977d2563e602"),
                            ScenarioId = new Guid("303c1d09-c3ac-4953-a47b-58329bea4bcc")
                        });
                });

            modelBuilder.Entity("VRAcademy.Api.Persistence.Entities.EnrollmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("EnrolledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExamId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Enrollments", (string)null);
                });

            modelBuilder.Entity("VRAcademy.Api.Persistence.Entities.TrainingScenarioEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DescriptionSr")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("int");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("NameSr")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("RiskCategory")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TrainingScenarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c77fe939-98ee-4ca5-9f61-0d8f9d31f2b2"),
                            Code = "fire-protection",
                            DescriptionEn = "Risk recognition, evacuation, equipment selection, and correct response.",
                            DescriptionSr = "Prepoznavanje rizika, evakuacija, izbor opreme i pravilno reagovanje.",
                            EstimatedMinutes = 35,
                            NameEn = "Fire protection",
                            NameSr = "Protivpozarna zastita",
                            RiskCategory = "Safety"
                        },
                        new
                        {
                            Id = new Guid("0d91384d-6c32-4f84-89c6-2bc378d01c18"),
                            Code = "radioactive-materials",
                            DescriptionEn = "Protective equipment, exposure control, and procedural checks.",
                            DescriptionSr = "Zastitna oprema, kontrola izlozenosti i proceduralne provere.",
                            EstimatedMinutes = 45,
                            NameEn = "Radioactive material handling",
                            NameSr = "Upravljanje radioaktivnim materijalima",
                            RiskCategory = "Hazardous materials"
                        },
                        new
                        {
                            Id = new Guid("bf90d0a8-f907-40fc-9450-bc6ec237bcb9"),
                            Code = "chemical-waste",
                            DescriptionEn = "Classification, labeling, storage, and spill response.",
                            DescriptionSr = "Klasifikacija, obelezavanje, skladistenje i reakcija na prosipanje.",
                            EstimatedMinutes = 40,
                            NameEn = "Chemical waste management",
                            NameSr = "Upravljanje hemijskim otpadom",
                            RiskCategory = "Waste management"
                        },
                        new
                        {
                            Id = new Guid("ffdb0364-47e2-4f4d-96b3-38675ba0938a"),
                            Code = "construction-waste",
                            DescriptionEn = "Material sorting, safe work, and waste flow tracking.",
                            DescriptionSr = "Razdvajanje materijala, bezbedan rad i pracenje tokova otpada.",
                            EstimatedMinutes = 30,
                            NameEn = "Construction waste management",
                            NameSr = "Upravljanje gradjevinskim otpadom",
                            RiskCategory = "Waste management"
                        },
                        new
                        {
                            Id = new Guid("c391aa43-b3c6-4876-93db-fca11143e2b5"),
                            Code = "electronic-waste",
                            DescriptionEn = "Sorting devices, batteries, cables, and sensitive components.",
                            DescriptionSr = "Sortiranje uredjaja, baterija, kablova i osetljivih komponenti.",
                            EstimatedMinutes = 35,
                            NameEn = "Electronic waste management",
                            NameSr = "Upravljanje elektronskim otpadom",
                            RiskCategory = "Waste management"
                        },
                        new
                        {
                            Id = new Guid("2a2d3685-1488-4d53-bd78-b82bb3a4c0d0"),
                            Code = "biomedical-waste",
                            DescriptionEn = "Separation, packaging, and temporary storage of healthcare waste.",
                            DescriptionSr = "Razdvajanje, pakovanje i privremeno skladistenje zdravstvenog otpada.",
                            EstimatedMinutes = 40,
                            NameEn = "Biomedical waste management",
                            NameSr = "Upravljanje biomedicinskim otpadom",
                            RiskCategory = "Healthcare safety"
                        },
                        new
                        {
                            Id = new Guid("ccb1504c-7ecb-4558-8634-5dacfdb1aec4"),
                            Code = "first-aid",
                            DescriptionEn = "Situation assessment, CPR, bleeding control, and correct use of an AED.",
                            DescriptionSr = "Procena situacije, KPR, kontrola krvarenja i pravilna upotreba AED uredjaja.",
                            EstimatedMinutes = 30,
                            NameEn = "First Aid Training",
                            NameSr = "Prva pomoc",
                            RiskCategory = "Emergency response"
                        },
                        new
                        {
                            Id = new Guid("6140c520-3b69-4019-923e-c2b402a05a96"),
                            Code = "working-at-heights",
                            DescriptionEn = "Fall hazard recognition, equipment selection, and safe movement at height.",
                            DescriptionSr = "Prepoznavanje rizika od pada, izbor opreme i bezbedno kretanje na visini.",
                            EstimatedMinutes = 30,
                            NameEn = "Working at Heights",
                            NameSr = "Rad na visini",
                            RiskCategory = "Work at height"
                        },
                        new
                        {
                            Id = new Guid("80286c22-aa3f-457c-a308-f01542307c02"),
                            Code = "forklift-safety",
                            DescriptionEn = "Vehicle inspection, safe operation, load handling, and workplace navigation.",
                            DescriptionSr = "Pregled vozila, bezbedno upravljanje, rukovanje teretom i kretanje kroz radnu zonu.",
                            EstimatedMinutes = 30,
                            NameEn = "Forklift Safety",
                            NameSr = "Bezbedno upravljanje viljuskarom",
                            RiskCategory = "Industrial vehicles"
                        },
                        new
                        {
                            Id = new Guid("f21e5460-36b5-4fe1-b3c7-2d1b9f0c6694"),
                            Code = "lockout-tagout",
                            DescriptionEn = "Energy source identification, isolation, lockout, and safe equipment verification.",
                            DescriptionSr = "Identifikacija izvora energije, izolacija, zakljucavanje i bezbedna provera opreme.",
                            EstimatedMinutes = 25,
                            NameEn = "Lockout / Tagout",
                            NameSr = "Lockout/Tagout (LOTO)",
                            RiskCategory = "Energy control"
                        },
                        new
                        {
                            Id = new Guid("5666ad20-8b6e-497f-aa65-5d74003b9fc3"),
                            Code = "personal-protective-equipment",
                            DescriptionEn = "Risk assessment, selection, inspection, correct use, and maintenance of PPE.",
                            DescriptionSr = "Procena rizika, izbor, pregled, pravilno koriscenje i odrzavanje zastitne opreme.",
                            EstimatedMinutes = 20,
                            NameEn = "Personal Protective Equipment",
                            NameSr = "Licna zastitna oprema",
                            RiskCategory = "Personal protection"
                        },
                        new
                        {
                            Id = new Guid("5eec99b0-5277-4d75-b2c4-8db0587495d1"),
                            Code = "chemical-safety",
                            DescriptionEn = "Label recognition, safe chemical handling, and spill response.",
                            DescriptionSr = "Prepoznavanje oznaka, bezbedno rukovanje hemikalijama i reagovanje pri prosipanju.",
                            EstimatedMinutes = 30,
                            NameEn = "Chemical Safety",
                            NameSr = "Hemijska bezbednost",
                            RiskCategory = "Chemical safety"
                        },
                        new
                        {
                            Id = new Guid("e357ce88-65e5-413c-acb3-6b6a8ac35b08"),
                            Code = "electrical-safety",
                            DescriptionEn = "Electrical hazard recognition, safe work practices, and emergency response.",
                            DescriptionSr = "Prepoznavanje elektricnih rizika, bezbedan rad i reagovanje u vanrednim situacijama.",
                            EstimatedMinutes = 30,
                            NameEn = "Electrical Safety",
                            NameSr = "Elektricna bezbednost",
                            RiskCategory = "Electrical safety"
                        },
                        new
                        {
                            Id = new Guid("60a98bf7-169c-42ef-ba03-fad6e6494c30"),
                            Code = "confined-space-entry",
                            DescriptionEn = "Space assessment, atmospheric testing, work permits, and rescue procedures.",
                            DescriptionSr = "Procena prostora, merenje atmosfere, dozvola za rad i postupci spasavanja.",
                            EstimatedMinutes = 30,
                            NameEn = "Confined Space Entry",
                            NameSr = "Ulazak u zatvoreni prostor",
                            RiskCategory = "Confined spaces"
                        },
                        new
                        {
                            Id = new Guid("2f0339c9-8371-45d2-a844-2d208468dad4"),
                            Code = "emergency-evacuation",
                            DescriptionEn = "Alarm recognition, exit selection, assisting others, and safe assembly.",
                            DescriptionSr = "Prepoznavanje alarma, izbor izlaza, pomoc kolegama i bezbedno okupljanje.",
                            EstimatedMinutes = 25,
                            NameEn = "Emergency Evacuation",
                            NameSr = "Hitna evakuacija",
                            RiskCategory = "Emergency response"
                        },
                        new
                        {
                            Id = new Guid("00cf06fa-8954-46c3-be43-2276b24864b4"),
                            Code = "industrial-machinery-safety",
                            DescriptionEn = "Machine inspection, guard checks, safe startup, operation, and shutdown.",
                            DescriptionSr = "Pregled masine, provera zastita, bezbedno pokretanje i zaustavljanje opreme.",
                            EstimatedMinutes = 30,
                            NameEn = "Safe Operation of Industrial Machinery",
                            NameSr = "Bezbedno rukovanje industrijskim masinama",
                            RiskCategory = "Machinery safety"
                        },
                        new
                        {
                            Id = new Guid("5bd2218a-d12f-4489-a6f4-de90321c3289"),
                            Code = "laboratory-safety",
                            DescriptionEn = "Safe work with samples, laboratory equipment, chemicals, and contamination.",
                            DescriptionSr = "Bezbedan rad sa uzorcima, laboratorijskom opremom, hemikalijama i kontaminacijom.",
                            EstimatedMinutes = 30,
                            NameEn = "Laboratory Safety",
                            NameSr = "Bezbednost u laboratoriji",
                            RiskCategory = "Laboratory safety"
                        },
                        new
                        {
                            Id = new Guid("a6f0a23f-0d19-4af4-b4a2-75525d82c53b"),
                            Code = "hazardous-material-handling",
                            DescriptionEn = "Receiving, labeling, segregation, transport, and storage of hazardous materials.",
                            DescriptionSr = "Prijem, oznacavanje, razdvajanje, transport i skladistenje opasnih materijala.",
                            EstimatedMinutes = 30,
                            NameEn = "Hazardous Material Handling",
                            NameSr = "Rukovanje opasnim materijalima",
                            RiskCategory = "Hazardous materials"
                        },
                        new
                        {
                            Id = new Guid("3ba2f8b1-126d-4251-ae77-ea977be1304b"),
                            Code = "construction-site-safety",
                            DescriptionEn = "Hazard recognition, safe movement, work zones, scaffolding, and access control.",
                            DescriptionSr = "Prepoznavanje rizika, bezbedno kretanje, radne zone, skele i kontrola pristupa.",
                            EstimatedMinutes = 30,
                            NameEn = "Construction Site Safety",
                            NameSr = "Bezbednost na gradilistu",
                            RiskCategory = "Construction safety"
                        },
                        new
                        {
                            Id = new Guid("493d682f-7cbd-445a-a18f-2a2d05f55434"),
                            Code = "crane-suspended-loads",
                            DescriptionEn = "Lift planning, exclusion zones, communication, and response to unstable loads.",
                            DescriptionSr = "Planiranje dizanja, bezbedne zone, komunikacija i reagovanje pri nestabilnom teretu.",
                            EstimatedMinutes = 30,
                            NameEn = "Working Near Cranes and Suspended Loads",
                            NameSr = "Rad u blizini dizalica i visecih tereta",
                            RiskCategory = "Lifting operations"
                        },
                        new
                        {
                            Id = new Guid("2ecb069d-56eb-4b12-848e-6fb847f0352a"),
                            Code = "gas-leak-response",
                            DescriptionEn = "Leak recognition, alarm activation, area isolation, and safe evacuation.",
                            DescriptionSr = "Prepoznavanje curenja, aktiviranje alarma, izolacija zone i bezbedna evakuacija.",
                            EstimatedMinutes = 30,
                            NameEn = "Gas Leak Response",
                            NameSr = "Reagovanje pri curenju gasa",
                            RiskCategory = "Emergency response"
                        },
                        new
                        {
                            Id = new Guid("a6bfca41-c56d-4d4d-a38c-016e94d8b841"),
                            Code = "warehouse-logistics-safety",
                            DescriptionEn = "Safe movement, load stacking, equipment handling, and logistics risk control.",
                            DescriptionSr = "Bezbedno kretanje, slaganje tereta, rukovanje opremom i kontrola logistickih rizika.",
                            EstimatedMinutes = 25,
                            NameEn = "Warehouse and Logistics Safety",
                            NameSr = "Bezbednost u skladistu i logistici",
                            RiskCategory = "Logistics safety"
                        },
                        new
                        {
                            Id = new Guid("de341505-37ae-4dde-b647-7a2b7ae0094d"),
                            Code = "drone-operation-fpv",
                            DescriptionEn = "Pre-flight checks, safe operation, FPV navigation, and incident response.",
                            DescriptionSr = "Predletna provera, bezbedno upravljanje, FPV navigacija i reagovanje na incidente.",
                            EstimatedMinutes = 30,
                            NameEn = "Drone Operation and FPV Navigation",
                            NameSr = "Upravljanje dronom i FPV navigacija",
                            RiskCategory = "Drone operations"
                        },
                        new
                        {
                            Id = new Guid("303c1d09-c3ac-4953-a47b-58329bea4bcc"),
                            Code = "drone-search-rescue",
                            DescriptionEn = "Mission planning, aerial search, casualty location, and rescue coordination.",
                            DescriptionSr = "Planiranje misije, vazdusna pretraga, lociranje osobe i koordinacija spasavanja.",
                            EstimatedMinutes = 35,
                            NameEn = "Drone-Assisted Search and Rescue",
                            NameSr = "Potraga i spasavanje uz pomoc drona",
                            RiskCategory = "Search and rescue"
                        });
                });

            modelBuilder.Entity("VRAcademy.Api.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varbinary(128)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varbinary(64)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("VRAcademy.Api.Persistence.Entities.WorkerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "EmployeeNumber")
                        .IsUnique();

                    b.ToTable("Workers", (string)null);
                });

            modelBuilder.Entity("VRAcademy.Api.Persistence.Entities.AuthSessionEntity", b =>
                {
                    b.HasOne("VRAcademy.Api.Persistence.Entities.UserEntity", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VRAcademy.Api.Persistence.Entities.CertificateEntity", b =>
                {
                    b.HasOne("VRAcademy.Api.Persistence.Entities.CourseEntity", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VRAcademy.Api.Persistence.Entities.WorkerEntity", "Worker")
                        .WithMany("Certificates")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("VRAcademy.Api.Persistence.Entities.CourseScenarioEntity", b =>
                {
                    b.HasOne("VRAcademy.Api.Persistence.Entities.CourseEntity", "Course")
                        .WithMany("CourseScenarios")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VRAcademy.Api.Persistence.Entities.TrainingScenarioEntity", "Scenario")
                        .WithMany("CourseScenarios")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("VRAcademy.Api.Persistence.Entities.EnrollmentEntity", b =>
                {
                    b.HasOne("VRAcademy.Api.Persistence.Entities.CourseEntity", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VRAcademy.Api.Persistence.Entities.WorkerEntity", "Worker")
                        .WithMany("Enrollments")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("VRAcademy.Api.Persistence.Entities.UserEntity", b =>
                {
                    b.HasOne("VRAcademy.Api.Persistence.Entities.CompanyEntity", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("VRAcademy.Api.Persistence.Entities.WorkerEntity", b =>
                {
                    b.HasOne("VRAcademy.Api.Persistence.Entities.CompanyEntity", "Company")
                        .WithMany("Workers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("VRAcademy.Api.Persistence.Entities.CompanyEntity", b =>
                {
                    b.Navigation("Users");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("VRAcademy.Api.Persistence.Entities.CourseEntity", b =>
                {
                    b.Navigation("CourseScenarios");
                });

            modelBuilder.Entity("VRAcademy.Api.Persistence.Entities.TrainingScenarioEntity", b =>
                {
                    b.Navigation("CourseScenarios");
                });

            modelBuilder.Entity("VRAcademy.Api.Persistence.Entities.UserEntity", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("VRAcademy.Api.Persistence.Entities.WorkerEntity", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
